#!/bin/bash

icon="/usr/share/pixmaps/SysClean/rating.png"
sensors="/usr/share/pixmaps/SysClean/sensors.png"
cclean="/usr/share/pixmaps/SysClean/ccleaner.png"
gamemode="/usr/share/pixmaps/SysClean/render-setup.png"

function Delete() {
    zenity --window-icon="$cclean" --question --text="удалить старые файлы ?" --title "DELETE" --height=200 --width=400

    if [[ $? == 0 ]]; then

        rm -rf /home/*/.local/share/Trash/*/** 

        bleachbit --list-cleaners >/home/$USER/.local/share/cleaners.list

        sed -i '/system.free_disk_space/d' /home/$USER/.local/share/cleaners.list
        sed -i '/apt.autoclean/d' /home/$USER/.local/share/cleaners.list
        sed -i '/apt.autoremove/d' /home/$USER/.local/share/cleaners.list
        sed -i '/apt.clean/d' /home/$USER/.local/share/cleaners.list
        sed -i '/apt.package_lists/d' /home/$USER/.local/share/cleaners.list
        sed -i '/system.memory/d' /home/$USER/.local/share/cleaners.list
        sed -i '/dnf.autoremove/d' /home/$USER/.local/share/cleaners.list
        sed -i '/dnf.clean_all/d' /home/$USER/.local/share/cleaners.list
        #куки 
        sed -i '/chromium.cookies/d' /home/$USER/.local/share/cleaners.list
        sed -i '/chromium.passwords/d' /home/$USER/.local/share/cleaners.list
        sed -i '/discord.cookies/d' /home/$USER/.local/share/cleaners.list
        sed -i '/epiphany.passwords/d' /home/$USER/.local/share/cleaners.list
        sed -i '/firefox.passwords/d' /home/$USER/.local/share/cleaners.list
        sed -i '/firefox.cookies/d' /home/$USER/.local/share/cleaners.list
        sed -i '/opera.passwords/d' /home/$USER/.local/share/cleaners.list
        sed -i '/opera.cookies/d' /home/$USER/.local/share/cleaners.list
        sed -i '/waterfox.passwords/d' /home/$USER/.local/share/cleaners.list
        
        
        xterm -e bleachbit -c $(cat /home/$USER/.local/share/cleaners.list)

        xterm -e sweeper --automatic 
        sleep 3

        #почти тоже самое от рута
        zenity --window-icon="$cclean" --question --text="Отчистить от Суперпользователя?" --title "DELETE ROOT" --height=200 --width=400
        if [[ $? == 0 ]]; then
            pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY bash /etc/init.d/SysCleanRoot
        fi
    fi
}

function Sensors() {

    cpu_temp=$(sensors)
    zenity --info --window-icon="$sensors" --text="Система: $cpu_temp" —-title="Показания датчиков" --height=200 --width=400
}

function Gamemode() {

    prog=$(zenity --window-icon="$gamemode" --entry --title="Gamemoderun" --text="Укажите название программы" --entry-text="firefox" --height=200 --width=400)

    if [ -n $prog ]; then
        gamemoderun $prog || zenity --window-icon="$gamemode" --error --text="Такого приложения не найдено" --height=200 --width=400
    fi
}

while true; do
    choice=$(zenity --window-icon="$icon" --list --imagelist --width=600 --height=320 --column="Icon" --column="Описание" --text="" \
        "$cclean" "Удалить журналы, архивы, остатки файлов конфигураций, кеши и т.д." \
        "$sensors" "Отобразить показания датчиков: температуру и т.д." \
        "$gamemode" "Запустить программу в режиме \"Gamemode\" ")

    case "$choice" in

    $cclean) Delete ;;
    $sensors) Sensors ;;
    $gamemode) Gamemode ;;
    *) break ;;

    esac

done

exit 0
