#!/bin/bash

xterm -e "rm -rfv /root/.local/share/Trash/*/** 

bleachbit --list-cleaners  > cleaners.list

sed -i '/system.free_disk_space/d'  cleaners.list
sed -i '/system.memory/d' cleaners.list

bleachbit -c $(cat cleaners.list)  

aptitude purge ~c -y 2> /dev/null & sleep 5" &
    
exit 0
