#!/bin/bash

rm -fv /usr/share/applications/SysClean.desktop
rm -fv /usr/bin/SysClean
rm -fv /etc/init.d/SysCleanRoot
rm -fv /etc/init.d/UnSysClean
rm -rfv /usr/share/pixmaps/SysClean

rm cleaners.list
rm /root/cleaners.list

aptitude remove $(cat /tmp/appdel) -y
aptitude purge ~c -y

update-desktop-database
update-icon-caches /usr/share/pixmaps/*

exit 0
